export const successPostfix = "_SUCCESS";
export const failurePostfix = "_FAILURE";

export const Modals = {
  NONE: "NONE",
  SIGNIN: "SIGNIN",
  SIGNUP: "SIGNUP",
};

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";

export const FETCH_CATEGORIES_FOR_TABBAR = "FETCH_CATEGORIES_FOR_TABBAR";
export const FETCH_CATEGORIES_FOR_TABBAR_SUCCESS =
  "FETCH_CATEGORIES_FOR_TABBAR_SUCCESS";
export const FETCH_CATEGORIES_FOR_TABBAR_FAILURE =
  "FETCH_CATEGORIES_FOR_TABBAR_FAILURE";

export const FETCH_CATEGORY_DETAIL = "FETCH_CATEGORY_DETAIL";
export const FETCH_CATEGORY_DETAIL_SUCCESS = "FETCH_CATEGORY_DETAIL_SUCCESS";
export const FETCH_CATEGORY_DETAIL_FAILURE = "FETCH_CATEGORY_DETAIL_FAILURE";

export const FETCH_PHOTOS = "FETCH_PHOTOS";
export const FETCH_PHOTOS_SUCCESS = "FETCH_PHOTOS_SUCCESS";
export const FETCH_PHOTOS_FAILURE = "FETCH_PHOTOS_FAILURE";

export const FETCH_PHOTO_DETAIL = "FETCH_PHOTO_DETAIL";
export const FETCH_PHOTO_DETAIL_SUCCESS = "FETCH_PHOTO_DETAIL_SUCCESS";

export const FETCH_USER_INFO = "FETCH_USER_INFO";
export const FETCH_USER_INFO_SUCCESS = "FETCH_USER_INFO_SUCCESS";

export const SHOW_SIGNIN_MODAL = "SHOW_SIGNIN_MODAL";
export const HIDE_SIGNIN_MODAL = "HIDE_SIGNIN_MODAL";

export const SHOW_SIGNUP_MODAL = "SHOW_SIGNUP_MODAL";
export const HIDE_SIGNUP_MODAL = "HIDE_SIGNUP_MODAL";
