export const successPostfix = "_SUCCESS";
export const failurePostfix = "_FAILURE";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";

export const FETCH_CATEGORY_DETAIL = "FETCH_CATEGORY_DETAIL";
export const FETCH_CATEGORY_DETAIL_SUCCESS = "FETCH_CATEGORY_DETAIL_SUCCESS";
export const FETCH_CATEGORY_DETAIL_FAILURE = "FETCH_CATEGORY_DETAIL_FAILURE";

export const FETCH_PHOTOS = "FETCH_PHOTOS";
export const FETCH_PHOTOS_SUCCESS = "FETCH_PHOTOS_SUCCESS";
export const FETCH_PHOTOS_FAILURE = "FETCH_PHOTOS_FAILURE";

export const FETCH_PHOTO_DETAIL = "FETCH_PHOTO_DETAIL";
export const FETCH_PHOTO_DETAIL_SUCCESS = "FETCH_PHOTO_DETAIL_SUCCESS";
